jspage/urls.py
from django.urls import path
from . import views

app_name = "jspage"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginView, name='login'),
    path('profile/', views.index, name='index'),
    path('booksfinder/', views.books, name='books'),
    path('logout/', views.logoutView, name='logout')

]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jspage.urls')),
    

]

jspage/models.py
from django.db import models

# Create your models here.

jspage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User




def index(request):
    return render(request, 'jspage.html')

def books(request):
    return render(request, 'books.html')

def home(request):
    context = {
        'greeting' : 'Selamat Datang di Website Kami',
        'phase' : 'login',
    }

    if request.user.is_authenticated:

        context['greeting'] = 'Selamat Datang ' + request.session["username"]
        context['phase'] = 'logout'


    return render(request, 'home.html', context)



def loginView(request):

    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('jspage:home')
        else:
            return render(request, 'login.html')

    if request.method == "POST":
        if len(request.POST) == 3:
            username = request.POST["username"]
            password = request.POST["password"]


            user = authenticate(username=username, password=password)



            if user is not None:
                login(request, user)
                request.session["username"] = user.username
                return redirect('jspage:home')
            else:
                return redirect('jspage:login')

        elif len(request.POST) == 4:
            username = request.POST['username']
            email = request.POST['email']
            password = request.POST['password']

            user = User.objects.create_user(username=username, email=email, password=password)
            login(request, user)
            request.session["username"] = user.username
            return redirect('jspage:home')


    # print(request.user)
    #
    # username_1 = "saya"
    # password_1 = "saya"
    # user = authenticate(request, username=username_1, password=password_1)
    # login(request, user)


@login_required
def logoutView(request):
    request.session.flush()
    if request.method == "GET":

        if request.user.is_authenticated:
            logout(request)
        return redirect('jspage:home')

    # print(request.user)
    #
    # username_1 = "saya"
    # password_1 = "saya"
    # user = authenticate(request, username=username_1, password=password_1)
    # login(request, user)

jspage/templates/base.html
<!DOCTYPE html>
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>

    {% block head %}
    {% include 'head.html' %}
    {% endblock head %}

</head>

<body class ='body'>
  <nav class="navbar sticky-top navbar-expand-md navbar-dark my-nav">

     <a class="navbar-brand" href="#">LRN</a>

     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
         <ul class= "navbar-nav ml-auto">
           <li class= "nav-item" >
             <a href="{% url 'jspage:home' %}" class = "nav-link">Home</a>
           </li>
           <li class= "nav-item" >
             <a href="{% url 'jspage:index' %}" class = "nav-link">Profile</a>
           </li>
           <li class= "nav-item" >
             <a href="{% url 'jspage:books' %}" class = "nav-link">Search Books</a>
           </li>
           <li class= "nav-item" >
             <a href="#" class = "nav-link theme">Change Theme</a>
           </li>
         </ul>
     </div>
 </nav>



{% block body %}

{% endblock body %}
<script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>

<script src = "{% static 'js/jquery.js' %}"></script>
<script src = "{% static 'js/jquery_theme.js' %}"></script>
<script src = "{% static 'js/jquery_accordion.js' %}"></script>
<script src = "{% static 'js/bookfinder.js' %}"></script>

<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>


</body>


</html>

jspage/templates/books.html
{% extends 'base.html' %}
{% load static %}


{% block body %}


<div class="background-col">

  <div class="container">
  <header class="text-center py-5 mb-4">

       <h1 class="font-weight-light head">Book Finder</h1>

  </header>
  </div>

  <div class="container">
      <div class="row">


        <div class="form-group shadow-textarea">
            <h5 class="font-weight-light description">Books</h5>
            <input id="search" placeholder="Title or Author">
            <button id="button" name="button">Search</button>

        </div>


      </div>



      <div class="row">



        <div id="results">



        </div>



      </div>






  </div>






</div>





{% endblock body %}

jspage/templates/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width =device-width">
<title>Lado's Profile</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

jspage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body class="background">

    <nav class="navbar sticky-top navbar-expand-md navbar-dark my-nav">

       <a class="navbar-brand" href="#">LRN</a>

       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
           <ul class= "navbar-nav ml-auto">
             <li class= "nav-item" >
               <a href="{% url 'jspage:home' %}" class = "nav-link">Home</a>
             </li>
             <li class= "nav-item" >
               <a href="{% url 'jspage:index' %}" class = "nav-link">Profile</a>
             </li>
             <li class= "nav-item" >
               <a href="{% url 'jspage:books' %}" class = "nav-link">Search Books</a>
             </li>
             <li class= "nav-item" >
               <a href="#" class = "nav-link theme">Change Theme</a>
             </li>
           </ul>
       </div>
   </nav>



    <div class="form">
		<h3>{{greeting}}</h3>
    
		{% if phase == "login" %}
		<button type="button" id="login" class="button button-block" onclick="window.location.href='{% url 'jspage:login' %}'">Log In / Sign Up</button>
		{% elif phase == "logout" %}
		<button type="button" id="logout" class="button button-block" onclick="window.location.href='{% url 'jspage:logout' %}'">Log Out</button>
		{% endif %}
	</div>




      <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>

      <script src = "{% static 'js/jquery.js' %}"></script>
      <script src = "{% static 'js/jquery_theme.js' %}"></script>
      <script src = "{% static 'js/jquery_accordion.js' %}"></script>
      <script src = "{% static 'js/bookfinder.js' %}"></script>
      <script src = "{% static 'js/login.js' %}"></script>


      <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
      <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
      <script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>

  </body>
</html>

jspage/templates/jspage.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


<div class="background-col">

  <div class="container">
  <header class="text-center py-5 mb-4">

       <h1 class="font-weight-light head">Profile</h1>

  </header>
  </div>

   <div class="container">
     <div class="row">
       <!-- Team Member 1 -->
       <div class="col-xl-3 col-md-6">
         <div class="card border-0 shadow">
           <img src="{% static 'img/lado.jpg' %}" class="card-img-top" alt="...">
           <div class="card-body text-center">
             <h5 class="card-title mb-0">Lado Rayhan Najib</h5>
             <div class="card-text text-black-50">Web Developer</div>
             <ul class="list-unstyled mb-0">
               <!-- Facebook -->
               <a class="p-2 fa-lg fb-ic" href="https://www.linkedin.com/in/lado-rayhan-b89206126/" target="_blank">
                 <i class="fab fa-linkedin text-black-50"> </i>
               </a>
               <!-- Twitter -->
               <a class="p-2 fa-lg tw-ic" href="https://twitter.com/najiblado" target="_blank" >
                 <i class="fab fa-twitter text-black-50"> </i>
               </a>
               <!-- Instagram -->
               <a class="p-2 fa-lg ins-ic" href="https://www.instagram.com/ladorayhann/" target="_blank">
                 <i class="fab fa-instagram text-black-50"> </i>
               </a>
             </ul>
           </div>
         </div>
       </div>

       <div class="col">
         <p class="text-justify description">
            Hello, my name is Lado Rayhan Najib and people usually call me Lado. I know my name is unique cause there is no one has the name "Lado" in my country.  I used to be called Rayhan, cause in my country its a common name.  But when I have a friend that has the same name, people get confused to call Rayhan.  I am a Computer Science student at the University of Indonesia (UI). Now I'm in the third term.  It's getting hard to learn as a Computer Science student at UI, but I always have this in my mind, <em>the harder you learn, the more you earn</em>.
         </p>
       </div>

       <div class="col">

           <header class="text-center">
                <h3 class="font-weight-light head">Biodata</h3>
           </header>


           <ul class="child">

               <li class='acc-list'>
                 <a class="panels" href="#">Activities</a>
                 <ul class="inside">
                     <li>Student</li>
                     <li>Playing Music, Band</li>
                     <li>Making Film, Short Movie, Movie Reviewer</li>
                     <li>Singing</li>
                     <li>Sports</li>
                 </ul>
               </li>

               <li class='acc-list'>
                 <a class="panels" href="#">Experiences</a>
                 <ul class="inside">
                   <li>Staff of Operational <strong>Setara 70</strong> </li>

                   <li>Staff of Operational <strong>INTEGER 2018</strong></li>
                   <li>Staff of Operational <strong>CGT Fasilkom UI 2018</strong></li>
                   <li>Staff of Operational <strong>COMPFEST 11</strong></li>
                 </ul>
               </li>

               <li class='acc-list'>
                 <a class="panels" href="#">Achievements</a>
                 <ul class="inside">
                   <li>1st place in high school chemistry olympiad</li>
                   <li>1st place students in Jakarta 70 High School 2016-2017</li>
                   <li>Got SNMPTN(Invitation Without Test) from the University of Indonesia</li>
                   <li>3th Place FIFA Tournament ZeusGaming 2018</li>
                 </ul>
               </li>

               <li class='acc-list'>
                 <a class="panels" href="#">Educations</a>
                 <ul class="inside">
                   <li>SDN 03 Pesanggrahan</li>
                   <li>SMPN 161 Jakarta</li>
                   <li>SMAN 70 Jakarta</li>
                   <li>University of Indonesia, Computer Science Undergraduate</li>
                 </ul>
               </li>

            </ul>

          </div>
       </div>



</div>





{% endblock body %}


<!-- <script>

// $(document).ready(function()){
//     //
//     // var count_bg = 0;
//     // var count_col = 0;
//     // var bg = ["#181818", "white"];
//     // var color = ["white", "#181818"];
//     $('.head').css('color', "green"]);
//
//
//     // $('.head').click(function(){
//     //
//     //     $('.background-col').css('background-color', "green"]);
//     //     $('.head').css('color', color[count_col]);
//     //     $('hr').css('color',color[count_col]);
//     //     $('greet').css('color', color[count_col++]);
//     //
//     //     if(count_bg == bg.length && count_col == color.length){
//     //         count_bg = 0;
//     //         count_col = 0;
//     //     }
//     //
//     // });
//   });
//
//   </script> -->

jspage/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width =device-width">
  <title>Login Page</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body class="background">

  <div class="form">
		<ul class="tab-group">
			<li class="tab active"><a id="title_login" href="#login">Log In</a></li>
			<li class="tab "><a id="title_signup" href="#signup">Sign Up</a></li>

		</ul>

		<div class="tab-content">
			<div id="login">

				<form method="POST">
					{% csrf_token %}

					<div class="field-wrap">
						<label>
						Username<span class="req">*</span>
						</label>
						<input class ="input" type="text" name="username" id="username_login" required autocomplete="off"/>
					</div>

					<div class="field-wrap">
						<label>
						Password<span class="req">*</span>
						</label>
						<input class="input" type="password" name="password" id="password_login" required autocomplete="off"/>
					</div>

					<button type="submit" id="submit_login" class="button button-block">Log In</button>

				</form>

			</div>

			<div id="signup">

				<form method="POST">
					{% csrf_token %}
					<div class="field-wrap">
						<label>
							Username<span class="req">*</span>
						</label>
						<input class="input" type="text" name="username" id="username_signup" required autocomplete="off" />
					</div>

					<div class="field-wrap">
						<label>
						Email Address<span class="req">*</span>
						</label>
						<input class="input" type="email" name="email" id="email_signup" required autocomplete="off"/>
					</div>

					<div class="field-wrap">
						<label>
						Set A Password<span class="req">*</span>
						</label>
						<input class="input" type="password" name="password" id="password_signup" required autocomplete="off"/>
					</div>

					<button type="submit" id="submit_signup" class="button button-block">SIGN UP</button>

				</form>

			</div>

		</div><!-- tab-content -->

	</div> <!-- /form -->






<script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>

<script src = "{% static 'js/jquery.js' %}"></script>
<script src = "{% static 'js/jquery_theme.js' %}"></script>
<script src = "{% static 'js/jquery_accordion.js' %}"></script>
<script src = "{% static 'js/bookfinder.js' %}"></script>
<script src = "{% static 'js/login.js' %}"></script>

<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>


</body>


</html>